# Generated by Django 3.1.2 on 2020-10-18 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='username',
            field=models.CharField(default='jon', max_length=100, verbose_name='Owner'),
            preserve_default=False,
        ),
    ]
